from sqlalchemy import Column, Integer, String, Float, DateTime
from .database import Base

class Accident(Base):
    __tablename__ = "accidents"

    id = Column(Integer, primary_key=True, index=True)
    pesid = Column(String)
    data_inversa = Column(String)
    dia_semana = Column(String)
    horario = Column(String)
    uf = Column(String)
    br = Column(Integer)
    km = Column(String)
    municipio = Column(String, index=True)
    causa_principal = Column(String)
    causa_acidente = Column(String)
    tipo_acidente = Column(String)
    classificacao_acidente = Column(String)
    fase_dia = Column(String)
    condicao_metereologica = Column(String)
    tipo_pista = Column(String)
    tracado_via = Column(String)
    tipo_veiculo = Column(String)
    marca = Column(String)
    ano_fabricacao_veiculo = Column(Integer)
    tipo_envolvido = Column(String)
    estado_fisico = Column(String)
    idade = Column(Integer)
    sexo = Column(String)
    ilesos = Column(Integer)
    feridos_leves = Column(Integer)
    feridos_graves = Column(Integer)
    mortos = Column(Integer)
    latitude = Column(Float)
    longitude = Column(Float)
    regional = Column(String)
    delegacia = Column(String)
    uop = Column(String)
